source 'https://rubygems.org'

gem 'dm-core',           '~> 1.0.2'
gem 'dm-aggregates',     '~> 1.0.2'
gem 'dm-migrations',     '~> 1.0.2'
gem 'dm-timestamps',     '~> 1.0.2'
gem 'dm-types',          '~> 1.0.2'
gem 'dm-validations',    '~> 1.0.2'
gem 'jeweler',           '1.8.8'
gem 'micronaut',         '>= 0.3.0'
gem 'rake',              '0.8.7'
