# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jm81-attach}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jared Morgan"]
  s.date = %q{2010-09-09}
  s.description = %q{This is a library I've developed for attachments, because I just don't like the others I've tried.}
  s.email = %q{jmorgan@morgancreative.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "examples/attach/attachment_example.rb",
     "examples/attach/samples.rb",
     "examples/attach_example.rb",
     "examples/example_helper.rb",
     "jm81-attach.gemspec",
     "lib/attach.rb",
     "lib/attach/attachable.rb",
     "lib/attach/attachment.rb",
     "lib/attach/version.rb",
     "lib/extensions/resize_matte.rb"
  ]
  s.homepage = %q{http://github.com/jm81/attach}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Yet another Attachments library (for DataMapper)}
  s.test_files = [
    "examples/attach/attachment_example.rb",
     "examples/attach/samples.rb",
     "examples/attach_example.rb",
     "examples/example_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, ["~> 1.0.2"])
      s.add_runtime_dependency(%q<dm-aggregates>, ["~> 1.0.2"])
      s.add_runtime_dependency(%q<dm-timestamps>, ["~> 1.0.2"])
      s.add_runtime_dependency(%q<dm-types>, ["~> 1.0.2"])
      s.add_runtime_dependency(%q<dm-validations>, ["~> 1.0.2"])
      s.add_development_dependency(%q<dm-migrations>, ["~> 1.0.2"])
      s.add_development_dependency(%q<micronaut>, [">= 0.3.0"])
    else
      s.add_dependency(%q<dm-core>, ["~> 1.0.2"])
      s.add_dependency(%q<dm-aggregates>, ["~> 1.0.2"])
      s.add_dependency(%q<dm-timestamps>, ["~> 1.0.2"])
      s.add_dependency(%q<dm-types>, ["~> 1.0.2"])
      s.add_dependency(%q<dm-validations>, ["~> 1.0.2"])
      s.add_dependency(%q<dm-migrations>, ["~> 1.0.2"])
      s.add_dependency(%q<micronaut>, [">= 0.3.0"])
    end
  else
    s.add_dependency(%q<dm-core>, ["~> 1.0.2"])
    s.add_dependency(%q<dm-aggregates>, ["~> 1.0.2"])
    s.add_dependency(%q<dm-timestamps>, ["~> 1.0.2"])
    s.add_dependency(%q<dm-types>, ["~> 1.0.2"])
    s.add_dependency(%q<dm-validations>, ["~> 1.0.2"])
    s.add_dependency(%q<dm-migrations>, ["~> 1.0.2"])
    s.add_dependency(%q<micronaut>, [">= 0.3.0"])
  end
end

